### ISSUE TITLE
Google Play bans self-updating Android apps

### ISSUE THREAD

**Issue by javiersantos** [atzcx/AppVerUpdater#5]
Hello!
[AppUpdater library](https://github.com/javiersantos/AppUpdater) developer here. I just want to let you know about a policy in the Google Play Developer Content Policy. It says:

> An app downloaded from Google Play may not modify, replace or update its own APK binary code using any method other than Google Play's update mechanism.

I was affected by this policy a year ago with [Beta Updater for WhatsApp](https://github.com/javiersantos/WhatsAppBetaUpdater) and the app was banned from Google Play. I advise you to put a clarification for users using this library.

More info [here](http://www.androidcentral.com/google-if-you-distribute-your-app-through-google-play-you-ll-update-it-through-google-play) and [here](http://arstechnica.com/information-technology/2013/04/google-bans-self-updating-android-apps-possibly-including-facebooks/).

Hope it helps.

**Comment by kaplanerkan** [comment]
Hi
i am not AppVerUpdater developper but only an app developper.

I do not need to publish my app on the playstore. I self set, install and
sell my app to my clients like restaurants...my customers dont need
playstore because they working only in Kiosk Mode. ..

Green
Erkan


Am 11.01.2017 12:04 AM schrieb "Javier Santos" <notifications@github.com>:

**Comment by javiersantos** [comment]
Of course. If you aren't going to publish your app on Google Play, then ignore this issue. This only applies for apps on Google Play.

**Comment by atzcx** [comment]
Hi, thank you for letting. I'll know

**Comment by Slayer91** [comment]
Is there anyway to make the download and update auto? Without any user interaction?
